version: "{build}"
skip_tags: true

environment:
  GOPATH: c:\gopath
  GOROOT: C:\go-x86

install:
- set PATH=%GOPATH%\bin;c:\go-x86\bin;%PATH%
- go version
- go env
- mkdir c:\gopath\bin
- mkdir %GOPATH%\src\github.com\hashicorp
- cd ..
- move consul %GOPATH%\src\github.com\hashicorp
- cd %GOPATH%\src\github.com\hashicorp\consul

build_script:
- make.bat

test_script:
- make.bat test

artifacts:
- path: c:/gopath/src/github.com/hashicorp/consul/bin/consul.exe
  name: consul
