version: "{build}"
skip_tags: true

environment:
  GOPATH: c:\gopath

install:
- go version
- dir c:\msys64\mingw64

build_script:
- set PATH=Cc:\msys64\mingw64\bin;C:\MINGW\bin\;%PATH%
- scripts\windows\build.bat

test_script:
- scripts\windows\verify_no_uuid.bat

artifacts:
- path: bin/consul.exe
  name: consul
