version: "{build}"
skip_tags: true

environment:
  GOPATH: c:\gopath
  GOROOT: c:\go

install:
- go version
- set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
- mkdir c:\gopath\bin
- mkdir %GOPATH%\src\github.com\hashicorp
- cd ..
- ren consul %GOPATH%\src\github.com\hashicorp\consul
- cd %GOPATH%\src\github.com\hashicorp
- set GOPATH
- go env

build_script:
#- set PATH=C:\msys64\mingw64\bin;C:\MINGW\bin\;%PATH%
- make.bat

test_script:
- make.bat test

artifacts:
- path: c:/gopath/src/github.com/hashicorp/consul/bin/consul.exe
  name: consul
