version: "{build}"
skip_tags: true

environment:
  GOPATH: c:\gopath

install:
- go version
- set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
- mkdir c:\gopath\bin
- set GOPATH
- set GOROOT
- go env

build_script:
#- set PATH=C:\msys64\mingw64\bin;C:\MINGW\bin\;%PATH%
- make.bat

test_script:
- make.bat test

artifacts:
- path: bin/consul.exe
  name: consul
