version: "{build}"
skip_tags: true

install:
- go version

build_script:
- scripts\windows\build.bat

test_script:
- scripts\windows\verify_no_uuid.bat

artifacts:
- path: bin/consul.exe
  name: consul
