version: "{build}"
skip_tags: true

environment:
  GOPATH: c:\gopath

install:
- go version
- set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
- mkdir %GOPATH%
#- dir c:\msys64\mingw64
#- where cc1.exe

build_script:
- set PATH=C:\msys64\mingw64\bin;C:\MINGW\bin\;%PATH%
- make.bat

test_script:
- scripts\windows\verify_no_uuid.bat

artifacts:
- path: bin/consul.exe
  name: consul
