version: "{build}"
skip_tags: true

environment:
  GOPATH: c:\gopath

install:
- go version

build_script:
- set PATH=C:\MINGW\bin\;%PATH%
- scripts\windows\build.bat

test_script:
- scripts\windows\verify_no_uuid.bat

artifacts:
- path: bin/consul.exe
  name: consul
