version: "{build}"
skip_tags: true

clone_folder: c:\gopath\src\github.com\hashicorp\consul

environment:
  GOPATH: c:\gopath
  GOROOT: C:\go-x86

install:
- set PATH=%GOPATH%\bin;c:\go-x86\bin;%PATH%
- go version
- go env
- mkdir c:\gopath\bin

build_script:
- make.bat

test_script:
- make.bat test

artifacts:
- path: c:/gopath/src/github.com/hashicorp/consul/bin/consul.exe
  name: consul
